### ISSUE TITLE
IOS version does not build with sdk 8.0.0.GA

### ISSUE THREAD

**Issue by rlustemberg** [hansemannn/titanium-crashlytics#12]
App build fails dumping the following to the build_iphone.log:

```
[TRACE]    "_gzclose", referenced from:
[TRACE]        -[CLSPackageReportOperation compressData:toPath:] in Crashlytics(CLSPackageReportOperation.o)
[TRACE]        -[ANSCompressLogOperation main] in Crashlytics(ANSCompressLogOperation.o)
[TRACE]    "_gzerror", referenced from:
[TRACE]        ___56-[CLSPackageReportOperation writeBytes:length:toGZFile:]_block_invoke in Crashlytics(CLSPackageReportOperation.o)
[TRACE]    "_inflateEnd", referenced from:
[TRACE]        pushwoosh::unzCloseCurrentFile(void*) in libcom.pushwoosh.module.a(libPushwoosh.a-x86_64-master.o)
[TRACE]    "_gzopen", referenced from:
[TRACE]        -[CLSPackageReportOperation compressData:toPath:] in Crashlytics(CLSPackageReportOperation.o)
[TRACE]        -[ANSCompressLogOperation main] in Crashlytics(ANSCompressLogOperation.o)
[TRACE]    "_gzwrite", referenced from:
[TRACE]        ___56-[CLSPackageReportOperation writeBytes:length:toGZFile:]_block_invoke in Crashlytics(CLSPackageReportOperation.o)
[TRACE]        -[ANSCompressLogOperation main] in Crashlytics(ANSCompressLogOperation.o)
[TRACE]  ld: symbol(s) not found for architecture x86_64
```

**Comment by janvennemann** [comment]
@hansemannn looks like `-lz` linker flag is missing in `module.xcconfig`

**Comment by hansemannn** [comment]
Yep, thats it. Never occurred to me because of our > 30 modules that most likely link it somewhere else already. @rlustemberg Please make a pull if possible!

**Comment by rlustemberg** [comment]
Will do asap

**Comment by rlustemberg** [comment]
Just made the PR

**Comment by hansemannn** [comment]
Thx!

**Comment by Sukirti-Vardhan** [comment]
> @hansemannn looks like `-lz` linker flag is missing in `module.xcconfig`

This works like charm. Thanks for sharing.
